### ISSUE TITLE
Template not working

### ISSUE THREAD

**Issue by lordesgar** [anime-skip/player#266]
I'm watching One Piece on Crunchyroll and I've started creating timestamps. The issue is that my templates dont seem to be applied. The image below is my template.

![ApCent_N5K9U73qCD](https://user-images.githubusercontent.com/111913841/186246368-3cb23f5f-6d93-4742-9d3a-5e1438cf5ba6.png)

It doesnt matter if I select All Episodes or just this season, whenever I open an episode that doesnt have any timestamps, it only uses this strange default setting which automatically skips to the preview of the next episode since there is no Canon timestamp;
 
![ApCent_lIWHLs84Fg](https://user-images.githubusercontent.com/111913841/186247183-1f30857c-4e47-40c8-b6ea-2de83e064236.jpg)

When I connect the episode to the extension, it tells me to create a new episode:

![tpn6r2lmJf](https://user-images.githubusercontent.com/111913841/186247771-abbd127c-2366-4c3c-9b65-47ef92ed3932.jpg)

I do that and the strange timestamps remain the same, my template is not applied:

![ApCent_19kFeLt6kD](https://user-images.githubusercontent.com/111913841/186248021-9b0887fa-b8d3-4dcb-afb6-b5ac6b45b3b6.jpg)

This is on Firefox version Version 103.0.2.

**Comment by aklinker1** [comment]
Nice to see a fellow firefox user out here.

I wonder if there are multiple templates, and it's choosing a bad one over your own.

I am also planning on removing the templates feature, or at least tweak it so you only get your own templates. Templates have been causing lots of incorrect timestamps to be submitted, like what you're seeing here. Might bring them back once some issues have been sorted out, might not. IMO even for shows like one peice, they're not too useful because timestamps are never quite in the same place.

**Comment by lordesgar** [comment]
Templates would be super useful for One Piece. Up to about episode 239 the openings are always in the beginning of the episode. Good to hear that you are gonna fix it :)
Being able to have your own personal templates would be awesome.

**Comment by aklinker1** [comment]
Continuing the conversation from your other comment...

> I'm assuming templates are user-specific and not shared by others?

Templates are shared by everyone, they are not individual. This is yet another source of "over-applying" timestamps as mentioned in 3rd checkbox. I'm going to make a change to the API so it only returns templates you own, that will be a good interim fix. We can continue the conversation over there.

Hopefully that's what's happening here, but I'll get this fixed as well if it's different.

**Comment by lordesgar** [comment]
Sounds like a good idea. Really like this extension, it's a great idea. Hope you'll add more sites in the future, like animixplay.
Btw, since you're here, I cant connect this episode on both crunchyroll and zoro.to:
https://beta.crunchyroll.com/watch/GY0970J9Y/the-man-who-is-loved-even-by-his-ship-usopps-tears
https://zoro.to/watch/one-piece-100?ep=2388

**Comment by aklinker1** [comment]
Uhh, seems like everything is down RN. No idea why. Can't visit the website, or change my preferences either. DNS isn't resolving....

```bash
$ dig www.anime-skip.com

; <<>> DiG 9.16.1-Ubuntu <<>> www.anime-skip.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 32211
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;www.anime-skip.com.            IN      A

;; Query time: 119 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Aug 23 18:55:27 CDT 2022
;; MSG SIZE  rcvd: 47

```

Looks like all my domains have gone down :/ WTF is this. Not related to this issue tho lol

**Comment by lordesgar** [comment]
Yikes, well hope it gets resolved soon.

**Comment by aklinker1** [comment]
@lordesgar everything appears to be back up. Let me know if the problem continues.

**Comment by aklinker1** [comment]
This has been fixed on the API side, and the change has been deployed. @lordesgar let me know if you're still not getting your own templates for One Piece, it should be working right now.

**Comment by lordesgar** [comment]
> This has been fixed on the API side, and the change has been deployed. @lordesgar let me know if you're still not getting your own templates for One Piece, it should be working right now.

I'm having some issues with the templates. I no longer get any default timestamps at all when I connect a new episode, which is probably a good sign, but I dont get my templates either.
Here is the creation of the template:

![ApCent_Wmqm5dgbCc](https://user-images.githubusercontent.com/111913841/186956229-1dbbc9ce-cdab-44fe-8cd0-08ac0d452e36.png)
![1lGXH0M1fC](https://user-images.githubusercontent.com/111913841/186956263-d16338fc-34a1-4afe-a2a6-d339ff42ab5f.png)

Here is a new episode that has no timestamps:

![wOGYcrFWv4](https://user-images.githubusercontent.com/111913841/186956317-2cf4afa9-09eb-4354-b9c3-3f18ecf1af2e.png)
![PpgQtMuhxq](https://user-images.githubusercontent.com/111913841/186956346-4f962394-5c6f-4057-a241-227f38a87ad0.png)
![MnDs0Z7Gr4](https://user-images.githubusercontent.com/111913841/186956372-194fdf2f-dc27-4fb2-9cbf-51403bc25926.png)

Not sure if I'm doing something wrong, though.

**Comment by aklinker1** [comment]
I'll check this out today after work

**Comment by aklinker1** [comment]
Update: I've made some changes to the API and things are mostly working. You can create and consume your own templates, but you can't edit them... If you need to edit one, delete it and create a new one.

I'll keep working on getting the editing working tonight

**Comment by aklinker1** [comment]
Alright, templates should be working again 100%. Did a bunch of manual testing, and everything looks good to me. Re-open if you have any other issues.

**Comment by lordesgar** [comment]
@aklinker1 I can't re-open the issue, since I'm not a collaborator, but I'm unfortunately still having this issue. Here is my template:

![3ACBerVsoS](https://user-images.githubusercontent.com/111913841/187038853-c4cb04f9-4f44-468a-8f8a-56406403b190.png)

And here is the next unconnected episode:

![gAisy4VeTb](https://user-images.githubusercontent.com/111913841/187038881-948f4983-03f0-4dee-9138-1a5a289e32fa.png)

I'm assuming that only the latest created template is supposed to be used? Either way, the template that is applied is not one that I have created. Maybe it's an issue with my account? My username is "lumiere".

**Comment by aklinker1** [comment]
Hmm, good to know you can't reopen.

Thanks for the details... I'm confident it should be working now, I'll check out the DB and figure out what is going on in your case

**Comment by aklinker1** [comment]
Alright, apparently you have 11 active templates for one piece, and the player uses the first one with timestamps that matches the show/season you're one, so you're getting an old template you made instead of the newest. Here's a list of all the episodes you've defined templates on:

![Screenshot from 2022-08-29 07-29-14](https://user-images.githubusercontent.com/10101283/187201205-204e4f94-d660-40ab-871e-18d83c64093a.png)

You also already have a template for Season 4, so it's using that over you're latest "all episodes" one.

I can delete these for you if you'd like, and then you can start from a clean slate, or you can go back to all these episodes and delete the templates that are no longer needed.

Since the player doesn't really tell you which template is in use or let you choose between templates, it's difficult to figure out what's going on. I'll include a "timestamp source" picker in V2 that lets you select between all the different templates and matching timestamp sets.

**Comment by aklinker1** [comment]
Or just delete your latest season 4 template and the API change I just made will return the latest "all episodes template" you've made: https://github.com/anime-skip/public-api/pull/101

**Comment by lordesgar** [comment]
Just went back and deleted all the templates. It seems to be working now on my end 👍

**Comment by aklinker1** [comment]
Nice, good to hear 👍
